blank_issues_enabled: false
contact_links:
  - name: 💬 Questions and Help
    url: https://github.com/craftdottech/craft/discussions
    about: Please ask and answer questions here.
  - name: 🔒 Security Reports
    url: https://github.com/craftdottech/craft/security/policy
    about: Please review our security policy for reporting vulnerabilities.
